spring:
  profiles:
    active:
    - dev
---
server: 
  port: 8001
 
spring: 
  profiles: dev
  application:
    name: springcloud-zuul-gateway
 
eureka: 
  client: 
    service-url: 
      defaultZone:http://eureka9001.com:9001/eureka,http://eureka9002.com:9002/eureka,http://eureka9003.com:9003/eureka
  instance:
    instance-id: springcloud-zuul-8001
    prefer-ip-address: true 

zuul: 
  #统一前缀
  prefix: /liaoyuangui
  #禁用微服务名称访问
  ignored-services: "*" 
  # routes to serviceId 这里边是通过serviceid来绑定地址，当在路径后添加/api-a/   则是访问service-A对应的服务。
  routes:
    #服务id （服务名称） 
    mydept.serviceId: springcloud-person-select-test 
    mydept.path: /service/**
    #如果有多个服务则追加


info:
  app.name: springcloud-zuul
  company.name: www.liaoyuangui.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
---
